# Generated by Django 5.2.7 on 2025-12-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Alias shown in the app (defaults to username)', max_length=150, null=True),
        ),
    ]
