# Generated by Django 5.2.7 on 2025-11-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('succulent', 'Succulent'), ('herb', 'Herb'), ('fern', 'Fern'), ('flowering_plant', 'Flowering Plant'), ('vegetable', 'Vegetable'), ('foliage_plant', 'Foliage Plant')], default='foliage_plant', max_length=50)),
                ('care_level', models.CharField(blank=True, help_text='Overall care difficulty (e.g., Easy, Moderate)', max_length=50, null=True)),
                ('watering_schedule', models.CharField(choices=[('daily', 'Daily'), ('twice_weekly', 'Twice Weekly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('infrequent', 'Infrequent'), ('moderate', 'Moderate'), ('consistent', 'Consistent'), ('when_soil_is_dry', 'When Soil is Dry'), ('frequent', 'Frequent'), ('occasionally', 'Occasionally'), ('none', 'None')], default='weekly', help_text='How often to water the plant', max_length=50)),
                ('sunlight_preference', models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('partial_shade', 'Partial Shade'), ('full_shade', 'Full Shade'), ('bright_indirect_light', 'Bright Indirect Light'), ('indirect_light', 'Indirect Light'), ('low_light', 'Low Light'), ('medium_light', 'Medium Light')], default='bright_indirect_light', help_text='Amount of sunlight needed', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('pot_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'X-Large')], default='medium', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('water', 'water'), ('fertilize', 'fertilize'), ('prune', 'prune'), ('health_issue', 'Health Issue')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sunlight_hours', models.FloatField(blank=True, help_text='Number of hours of sunlight received (0-24)', null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
