# Generated by Django 5.2.7 on 2025-11-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('water', 'water'), ('fertilize', 'fertilize'), ('prune', 'prune')], max_length=20),
        ),
    ]
